export const tooltips = {
  program: {
    programId: "The unique identifier for this program.",
    programAddress: "The blockchain address associated with this program.",
    deploymentTransaction: "The transaction that deployed this program to the blockchain.",
    programOwner: "The address that owns and controls the program.",
    timesCalled: "The number of times this program has been executed on the blockchain.",
    similarPrograms: "Other programs that share similar functionality or code.",
  },
  transition: {
    transitionId: "The unique identifier for this transition.",
    transaction: "The transaction to which this transition belongs.",
    status: "The current state of the transition.",
    programId: "The unique identifier for the program involved in this transition.",
    functionName: "The name of the function executed in this transition.",
    transitionPublicKey: "The public key used to verify the transition.",
    transitionCommitment: "A cryptographic commitment associated with this transition.",
    signerCommitment: "A cryptographic commitment to the signer's authorization used to validate this transition.",
  },
  transaction: {
    transactionId: "The unique identifier for this transaction.",
    block: "The block number in which this transaction was included.",
    timestamp: "The exact time when the transaction was confirmed.",
    status: "The current state of the transaction.",
    type: "The category of the transaction (e.g., transfer, contract execution).",
    index: "The position of this transaction within the block.",
    totalFeeSpent: "The total transaction fee paid to process this transaction.",
    breakdown: "A detailed view of transaction costs and resources used.",
    transferType: "The type of transfer (e.g., public, private, public to private, private to public).",
  },
  address: {
    address: "The unique identifier for this account on the blockchain.",
    programName: "The name of the program that owns this address.",
    addressTag: "Name of wallet.",
    publicAnsNames: "Public Aleo Name Service names linked to this address.",
    website: "The official website or external page for this validator.",
    publicBalance: "The total amount of tokens currently held by this account, visible to everyone on the blockchain.",
    tokensStaked: "The amount of tokens locked to support a validator.",
    stakedToValidator: "The specific validator this address has staked tokens to.",
    withdrawalAddress: "The designated address where staked rewards can be withdrawn.",
    lifetimeStakeReward: "The total rewards earned from staking over time.",
    publicTokensReceived: "The total number of credits received by this address.",
    publicTokensSent: "The total number of credits sent from this address.",
    totalFeeSpent: "The cumulative transaction fees paid by this address.",
    programsDeployed: "The number of smart contracts or programs deployed by this address.",
    acceptedPuzzleSolutions: "Accepted puzzle solutions submitted by this address.",
    lifetimePuzzleReward: "The total rewards earned from solving cryptographic puzzles.",
  },
  validator: {
    tokensStakedToValidator: "The total amount of tokens staked by others to this validator.",
    openForStaking: "Indicates whether the validator is accepting new stakers.",
    commission: "The percentage of rewards taken by the validator for managing stakes.",
    uptime: "The percentage of time the validator was operational in the last 24 hours.",
  },
}