export const tooltips = {
  program: {
    programId: "The unique identifier for this program.",
    programAddress: "The Aleo address derived from this program ID.",
    deploymentTransaction: "The transaction that deployed this program to the blockchain.",
    programOwner: "The address that authorized this deployment.",
    timesCalled: "Indexed transitions that called this program.",
    similarPrograms: "Programs sharing AleoScan's structural feature hash.",
  },
  transition: {
    transitionId: "Hash of the function-tree root and transition commitment.",
    transaction: "The transaction to which this transition belongs.",
    status: "Whether the containing transaction was accepted, rejected, aborted, or remains unconfirmed.",
    programId: "The unique identifier for the program involved in this transition.",
    functionName: "The name of the function executed in this transition.",
    transitionPublicKey: "Ephemeral public key recovered from the request signature.",
    transitionCommitment: "The hash of the transition view key.",
    signerCommitment: "Hash of the signer x-coordinate and root transition view key.",
  },
  transaction: {
    transactionId: "The unique identifier for this transaction.",
    block: "The block that accepted, rejected, or aborted this transaction.",
    timestamp: "The timestamp of the block containing this transaction.",
    status: "Whether the transaction was accepted, rejected, aborted, or remains unconfirmed.",
    type: "The transaction variant. Transfers are Execute transactions.",
    index: "The position of this transaction within the block.",
    totalFeeSpent: "The explicit transaction fee plus any credits.aleo/split fee.",
    breakdown: "The costs that make up this transaction's total fee.",
    transferType: "The public and private visibility of the transfer.",
  },
  address: {
    address: "The Aleo address whose public on-chain and indexed activity is shown on this page.",
    programName: "The program ID whose derived program address matches this address.",
    addressTag: "A label assigned to this address in AleoScan's database.",
    publicAnsNames: "The primary Aleo Name Service name resolved for this address.",
    website: "The website recorded in AleoScan's validator metadata for this address.",
    publicBalance: "The public credits.aleo/account balance. Private records are excluded.",
    tokensStaked: "The public credits currently bonded by this address to a validator.",
    stakedToValidator: "The validator to which this address's public credits are currently bonded.",
    withdrawalAddress: "The address that receives public credits when this staker claims an unbonding.",
    lifetimeStakeReward: "The cumulative staking rewards AleoScan has attributed to this address.",
    publicTokensReceived: "Indexed public credits received through transfers and claimed unbondings.",
    publicTokensSent: "Indexed public credits spent through transfers and bonding.",
    totalFeeSpent: "The cumulative fee_public amount paid from this address's public credits.",
    programsDeployed: "The number of program deployments authorized by this address.",
    acceptedPuzzleSolutions: "Accepted puzzle solutions submitted by this address.",
    lifetimePuzzleReward: "The total rewards earned from solving cryptographic puzzles.",
  },
  validator: {
    tokensStakedToValidator: "Total bonded and prebonded stake, including self-stake and delegations.",
    openForStaking: "Whether credits.aleo currently accepts new delegations to this validator.",
    commission: "The percentage of delegator staking rewards retained by the validator.",
    uptime: "Quorum-subdag participation across eligible blocks in the last 24 hours.",
  },
}
